//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagerMan_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class inverters
    {
        public string invSerial { get; set; }
        public string intPart_item { get; set; }
        public string invHwVer { get; set; }
        public string invSwVer { get; set; }
        public int invSupplier { get; set; }
        public int prodNo { get; set; }
    
        public virtual productCatalog productCatalog { get; set; }
        public virtual suppliers suppliers { get; set; }
    }
}
