//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagerMan_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class panels
    {
        public string panelSerial { get; set; }
        public string panelCname { get; set; }
        public int panelSupplier { get; set; }
        public Nullable<System.DateTime> panelMFGDate { get; set; }
        public Nullable<double> panelCellclass { get; set; }
        public Nullable<double> panelEff { get; set; }
        public Nullable<double> panelFf { get; set; }
        public Nullable<double> panelVmp { get; set; }
        public Nullable<double> panelVoc { get; set; }
        public Nullable<double> panelImp { get; set; }
        public Nullable<double> panelIsc { get; set; }
        public Nullable<double> panelPmpp { get; set; }
        public int prodNo { get; set; }
    
        public virtual productCatalog productCatalog { get; set; }
        public virtual suppliers suppliers { get; set; }
    }
}
