//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagerMan_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class suppliers
    {
        public suppliers()
        {
            this.inverters = new HashSet<inverters>();
            this.panels = new HashSet<panels>();
            this.productCatalog = new HashSet<productCatalog>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool importReg { get; set; }
    
        public virtual activeInventory activeInventory { get; set; }
        public virtual ICollection<inverters> inverters { get; set; }
        public virtual ICollection<panels> panels { get; set; }
        public virtual passiveInventory passiveInventory { get; set; }
        public virtual ICollection<productCatalog> productCatalog { get; set; }
    }
}
